name: Release
on:
  push:
    branches:
      - main
      - dev
jobs:
  Create-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository source
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ github.event.head_commit.message }}
          release_name: GL v${{ github.event.head_commit.message }}
          body_path: release-notes.md
          draft: true
          prerelease: false

#  Build-Windows:
#    runs-on: windows-latest
#    steps:
  Build-and-release-Linux:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: |
          sudo apt install unzip git gdb wget curl cmake libx11-dev libglu1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev zlib1g-dev libasound2-dev libgtk2.0-dev libgtk-3-dev libjack-jackd2-dev jq zstd libpulse-dev pkg-config
      - name: get RACK SDK
        run: |
          cd ..
          wget https://vcvrack.com/downloads/Rack-SDK-latest-lin-x64.zip
          unzip Rack-SDK-latest-lin-x64.zip
          cd GL
          make dep && make dist
          ls dist
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ jobs.Create-release.steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: dist/GL-2.0.0-lin-x64.vcvplugin
          asset_name: GL-${{ github.event.head_commit.message }}-lin-x64.vcvplugin

          asset_content_type: application/octet-stream

#  Build-Mac:
#    runs-on: ubuntu-latest
#    steps:

